name: nfl_app
description: A new Flutter application.



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_number: ^1.0.3
  sms_autofill: ^1.2.5

  intl: ^0.16.1
  time_formatter: ^1.0.0+5
  flutter_slidable: ^0.5.7

  dotted_border: ^1.0.6

  http: ^0.12.2

  flutter_spinkit: ^4.1.2+1

  redux: ^4.0.0+3
  flutter_redux: ^0.6.0

  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0

  google_maps_flutter: ^0.5.32
  flutter_polyline_points: ^0.2.3
  # geolocator: ^6.0.0+4
  geolocator: ^5.3.2+2
  geocoding: ^1.0.3

  image_picker: ^0.6.7+7
  firebase_storage: ^4.0.0


  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5


  shared_preferences: ^0.5.10
  toast: ^0.1.5
  cupertino_icons: ^1.0.0
  store_redirect: ^1.0.2
  flutter_rounded_date_picker: 1.0.0
  dio: ^3.0.10
  geocoder: ^0.2.1
  vibration: ^1.4.0
  lite_rolling_switch: ^0.1.1
  cupertino_tabbar: ^1.0.1
  device_id: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/